### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by gregschmit** [mat813/rb-kqueue#13]
Hi, just noticed that there is a PR to fix an issue with this project on FreeBSD 12/13 (https://github.com/mat813/rb-kqueue/pull/12), but it hasn't been merged or reviewed, so people are stuck having to reference a git repo in their Gemfile because RubyGems doesn't have a version with that patch.

Is this project abandoned? I'd be happy to take over as maintainer of the project if you're too busy. Otherwise it would be nice to see that PR reviewed/merged and a new release out.

**Comment by mat813** [comment]
Ah, sorry about that, I admit I didn't have time recently to do as much OSS work as I once did. I still use this though, though, not yet on 12/13.

I could add you as a collaborator here so you can handle #12 and a new release, if you want.

**Comment by gregschmit** [comment]
Oh yeah I totally understand; yeah I'd be happy to be a contributor and release a new version with the patch.

**Comment by gregschmit** [comment]
Could you also please add my rubygems username (`gregschmit`) to the list of owners on this project in RubyGems.org?

**Comment by mat813** [comment]
Yes, I am trying to figure out what email I used all those years ago.

**Comment by mat813** [comment]
Done.

**Comment by gregschmit** [comment]
Awesome, thanks!
